steps:
  build:
    image: gcr.io/kaniko-project/executor:latest
    commands:
      - echo "=============================="
      - echo "开始构建 Docker 镜像"
      - echo "=============================="
      - /kaniko/executor
        --context=.
        --dockerfile=Dockerfile
        --destination=woodpecker-demo:test
        --no-push
